name: Push rockspec

on:
  workflow_run:
    workflows: ["Tests"]
    branches: [master]
    types:
      - completed
  push:
    tags:
       - '*'

env:
  ROCK_NAME: "metrics"

jobs:
  version-check:
    # We need this job to run only on push with tag.
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    runs-on: [ ubuntu-24.04 ]
    steps:
      - name: Check module version
        uses: tarantool/actions/check-module-version@master
        with:
          module-name: 'metrics'
          version-pre-extraction-hook: |
            require('test.rock_utils').assert_nonbuiltin('metrics')

  push-scm-rockspec:
    runs-on: [ ubuntu-24.04 ]
    if: github.ref == 'refs/heads/master' && github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@master

      - uses: tarantool/rocks.tarantool.org/github-action@master
        with:
          auth: ${{ secrets.ROCKS_AUTH }}
          files: ${{ env.ROCK_NAME }}-scm-1.rockspec

  push-tagged-rockspec:
    runs-on: [ ubuntu-24.04 ]
    if: startsWith(github.ref, 'refs/tags')
    needs: version-check
    steps:
      - uses: actions/checkout@master

      # https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
      - name: Set env
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Push release rockspec
        run: |
          sed \
            -e "s/branch = '.\+'/tag = '${GIT_TAG}'/g" \
            -e "s/version = '.\+'/version = '${GIT_TAG}-1'/g" \
            ${{ env.ROCK_NAME }}-scm-1.rockspec > ${{ env.ROCK_NAME }}-${GIT_TAG}-1.rockspec

      - uses: tarantool/rocks.tarantool.org/github-action@master
        with:
          auth: ${{ secrets.ROCKS_AUTH }}
          files: ${{ env.ROCK_NAME }}-${GIT_TAG}-1.rockspec
